version: '3.8'

services:
  api:
    container_name: "api_movies"
    restart: "no"
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - ./app:/var/www/html
    command:
      "php -S 0.0.0.0:8080 -t /var/www/html/"
    depends_on:
      - db
    networks:
      - backend
  db:
    platform: linux/x86_64
    container_name: "api_db"
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - "./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
      - db_data:/var/lib/mysql
    networks:
      - backend
volumes:
  db_data:
networks:
  backend: